name: 'add-milestone-to-issue'
description: 'Add a milestone to an issue'
inputs:
  repo:  # repo name
    description: 'Repository'
    required: true
  gh_token:
    description: 'PAT'
    required: true
  owner:
    description: 'Repo owner'
    required: true
  milestone_number:
    description: 'id of milestone to fetch'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
